### ISSUE TITLE
Task: Add basic CSS

### ISSUE THREAD

**Issue by alexander-gavrilov** [alexander-gavrilov/city-photographer#199]
\n\n**Acceptance Criteria:**\n- [x] Body has margin and overflow settings
- [x] Canvas has display, width, and height settings
- [x] Canvas fills the entire viewport

**Implementation Details:**
```css
body {
margin: 0;
padding: 0;
overflow: hidden;
}
canvas {
display: block;
width: 100vw;
height: 100vh;
}
```

**Location:** These styles should be placed in a `<style>` tag in the `<head>` section of index.html\n\n**Part of Story:** #11\n\nChild of #11
